# Note: I recommend compiling with 'make -j' (since many template instantiations are compiled)
# Note: 'make one' will compile a single template instantiation (to avoid the full 'make -j' deluge)

GPUTILS_INCDIR=../gputils/include
GPUTILS_LIBDIR=../gputils/lib

# FIXME hardcoded -arch=sm_86 here. What is best practice?
NVCC=nvcc -std=c++17 -arch=sm_86 -m64 -O3 -I$(GPUTILS_INCDIR) --compiler-options -Wall
SHELL := /bin/bash

.DEFAULT_GOAL: all
.PHONY: all one clean .FORCE

HFILES = \
  n2k.hpp \
  n2k_kernel.hpp

OFILES = \
  Correlator.o \
  kernel_table.o \
  precompute_offsets.o \
  template_instantiations/kernel_256.o \
  template_instantiations/kernel_512.o \
  template_instantiations/kernel_1024.o \
  template_instantiations/kernel_2048.o \
  template_instantiations/kernel_4096.o \
  template_instantiations/kernel_8192.o \
  template_instantiations/kernel_16384.o \
  template_instantiations/kernel_32768.o \
  template_instantiations/kernel_65536.o

XFILES = \
  test-correlator \
  time-correlator

SRCDIRS = . template_instantiations

all: $(XFILES)

# Compile a single template instantiation, to avoid the full 'make -j all' deluge
one: template_instantiations/kernel_4096.o

# Not part of 'make all', needs explicit 'make source_files.txt'
source_files.txt: .FORCE
	rm -f source_files.txt
	shopt -s nullglob && for d in $(SRCDIRS); do for f in $$d/*.cu $$d/*.hpp $$d/*.cuh; do echo $$f; done; done >$@

clean:
	rm -f $(XFILES) source_files.txt *~ template_instantiations/*.cu
	shopt -s nullglob && for d in $(SRCDIRS); do rm -f $$d/*~ $$d/*.o; done

%.o: %.cu $(HFILES)
	$(NVCC) -c -o $@ $<

template_instantiations/kernel_%.cu: template_instantiations/make-instantiation.py
	$< $@

test-correlator: test-correlator.o $(OFILES) $(GPUTILS_LIBDIR)/libgputils.a
	$(NVCC) -o $@ $^

time-correlator: time-correlator.o $(OFILES) $(GPUTILS_LIBDIR)/libgputils.a
	$(NVCC) -o $@ $^

# I prefer not to have make autodelete its autogenerated source files
.PRECIOUS: template_instantiations/kernel_%.cu
